version: "3"

services:
  php:
    container_name: chain-php
    image: chain-php
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    volumes:
      - ./src:/var/www/test
    working_dir: /var/www/test
